# Generated by Django 4.0.3 on 2022-03-29 01:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regiao',
            fields=[
                ('id_regiao', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_regiao', models.CharField(max_length=25)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
