# Generated by Django 4.0.3 on 2022-03-29 02:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fruta',
            fields=[
                ('id_fruta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_fruta', models.CharField(max_length=100)),
                ('id_regiao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regions.regiao')),
            ],
        ),
    ]
